#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm
#=================================================

name: Build_x86_64

on:
  release:
    types: [published]

  #push:
  #  branches:
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5

  #watch:
  #  types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set +e
          sudo -E apt-get update
          sudo -E apt-get -y upgrade
          sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libncursesw6 libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev npm
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone source code
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ./openwrt

      - name: Import external feeds
        run: |
          mkdir -p ./my-feeds
          pushd ./my-feeds
          git clone --depth 1 -b main https://github.com/sirpdboy/chatgpt-web ./luci-app-chatgpt
          git clone --depth 1 -b master https://github.com/jerrykuku/luci-theme-argon ./luci-theme-argon
          git clone --depth 1 -b master https://github.com/jerrykuku/luci-app-argon-config ./luci-app-argon-config
          git clone --depth 1 -b master https://github.com/derisamedia/luci-theme-alpha ./luci-theme-alpha
          git clone --depth 1 -b js https://github.com/sirpdboy/luci-theme-kucat ./luci-theme-kucat
          git clone --depth 1 -b main https://github.com/sirpdboy/luci-app-advancedplus ./luci-app-advancedplus
          git clone --depth 1 -b master https://github.com/pymumu/luci-app-smartdns ./luci-app-smartdns
          git clone --depth 1 -b master https://github.com/pymumu/openwrt-smartdns ./smartdns
          popd

      - name: Merge feed config
        run: |
          cp -f ./openwrt/feeds.conf.default ./feeds.conf.temp
          { echo "src-link my_feeds $(cd ./my-feeds && pwd)"; cat ./feeds-ext.conf; cat ./feeds.conf.temp; } > ./openwrt/feeds.conf.default
          rm -f ./feeds.conf.temp

      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f

      - name: List feeds config
        working-directory: ./openwrt
        run: |
          cat feeds.conf.default

      - name: Show installed feeds
        working-directory: ./openwrt/package/feeds
        run: |
          find ./ -type l

      - name: Configuration Customization - Build_x86_64
        env:
          CONFIG_FILE: "x86_64.config"
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x ./customize.sh && ./customize.sh
          cd openwrt && make defconfig

      - name: Download package
        working-directory: ./openwrt
        run: |
          make download -j$(nproc) V=s
          find dl -size -1024c -exec rm -f {} \;
          make download -j$(nproc) V=s

      - name: Build firmware
        working-directory: ./openwrt
        run: |
          make -j$(nproc) V=s

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: openwrt
          path: openwrt/bin

      - name: Upload to release
        run: |
          set +e
          pushd ./openwrt/bin
          zip -9vr ../../openwrt.zip ./
          popd
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release delete openwrt -y --cleanup-tag
          gh release create openwrt openwrt.zip ./openwrt/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz --latest
