#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm
#=================================================

name: Build_x86_64

on:
  release:
    types: [published]

  #push:
  #  branches:
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5

  #watch:
  #  types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set +e
          sudo -E apt-get update
          sudo -E apt-get -y upgrade
          sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev npm
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone source code & Import external feeds
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ./openwrt
          cat ./feeds-ext.conf >> ./openwrt/feeds.conf.default
          mkdir -p ./my-feeds
          pushd ./my-feeds
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon ./luci-theme-argon
          git clone -b 18.06 https://github.com/kiddin9/luci-theme-edge ./luci-theme-edge
          git clone -b master https://github.com/sirpdboy/luci-theme-opentopd ./luci-theme-opentopd
          git clone -b master https://github.com/esirplayground/luci-theme-atmaterial-ColorIcon ./luci-theme-atmaterial-ColorIcon
          git clone -b 18.06 https://github.com/jerrykuku/luci-app-argon-config ./luci-app-argon-config
          git clone -b main https://github.com/thinktip/luci-theme-neobird ./luci-theme-neobird
          git clone -b master https://github.com/Leo-Jo-My/luci-theme-opentomcat ./luci-theme-opentomcat
          git clone -b main https://github.com/sirpdboy/chatgpt-web ./luci-app-chatgpt
          popd
          echo "src-link my_feeds $(cd ./my-feeds && pwd)" >> ./openwrt/feeds.conf.default

      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f -p my_feeds
          ./scripts/feeds install -a -f

      - name: Configuration Customization - Build_x86_64
        env:
          CONFIG_FILE: "x86_64.config"
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x ./customize.sh && ./customize.sh
          cd openwrt && make defconfig

      - name: Download package
        working-directory: ./openwrt
        run: |
          make download -j$(nproc) V=s
          find dl -size -1024c -exec rm -f {} \;

      - name: Build firmware
        working-directory: ./openwrt
        run: |
          make -j$(nproc) V=s

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: openwrt
          path: openwrt/bin

      - name: Upload to release
        run: |
          set +e
          pushd ./openwrt/bin
          zip -9mvr ../../openwrt.zip ./
          popd
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release delete openwrt -y --cleanup-tag
          gh release create openwrt openwrt.zip --latest
  
