name: Cleanup old workflows
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  delete_workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
